# Generated by Django 4.2.6 on 2023-10-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagenTraduccion', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='traduccion',
            name='imagenTraduccion',
        ),
    ]
