# Generated by Django 4.2.6 on 2023-10-22 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_imagen_remove_traduccion_imagentraduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion',
            name='idImagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.imagen'),
        ),
    ]
