# Generated by Django 4.2.6 on 2023-10-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_traduccion_idimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagenTraduccion',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
