# Generated by Django 4.2.6 on 2023-10-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_imagen_imagentraduccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traduccion',
            old_name='idioma',
            new_name='idiomaImagen',
        ),
        migrations.AddField(
            model_name='traduccionobtenido',
            name='idiomaTraduccion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
