# Generated by Django 4.2.6 on 2023-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_rename_idioma_traduccion_idiomaimagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traduccionobtenido',
            name='calificacionTraduccion',
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='horaTraduccion',
            field=models.DateTimeField(null=True),
        ),
    ]
